### ISSUE TITLE
do not show warning if there are no unsaved changes

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1077]
<img width="879" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/b5f2ae7c-86ab-4d16-afd1-9d0075e66439">

**Comment by HRemonen** [comment]
Either get rid off the confirmation all at once or store information in query parameters that the user is editing a certain question and from that conclude that there might be unsaved changes.

--
Now it is possible to press the preview tab without any confirmation about unsaved changes which is not particularly inline with the overall design.
![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/81435393/8c1b2b27-1341-4335-8b20-d06e455bf4eb)

Getting rid of the confirmation might not introduce any problems because the editing is made one question at a time, so only little loss of information is possible

**Comment by HRemonen** [comment]
I have chosen to remove the window confirm entirely on commit b5f32d7. If we would like to have window confirm when there is unsaved changes then the confirmation would have to appear on page reload, navigate back, on other tab click, on browser window closing etc. It does not bring value to just check on the preview link click as it would not be uniform.
