### ISSUE TITLE
koulutusohjelman kysely: adding a student number betterments

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1123]
Each student is needed to "confirm" by pressing enter, space or any of the allowed delimeters so that the chip appears for the student number. 

Check out improvement where the unfinished input is also considered a student number input. This has to be done on submit, but it is quite a tricky process

--

<img width="809" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/74d36253-e29c-448f-aeca-49dd856d4087">

and

<img width="330" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/92d2027f-1e56-4cbb-9120-e376b81935a9">

but

<img width="453" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/edd03875-fb22-4962-85bb-11a52fe35561">

and

<img width="732" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/b4785749-2a91-4a36-bc42-6eb455e92d2a">

**Comment by HRemonen** [comment]
Each student is needed to "confirm" by pressing enter, space or any of the allowed delimeters so that the chip appears for the student number. 

Check out improvement where the unfinished input is also considered a student number input. This has to be done on submit, but it is quite a tricky process
