### ISSUE TITLE
"Perinnekieli"

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1261]
_"kurssin nimi on Perintökieli, ei perinnekieli. Voisitteko ystävällisesti muuttaa tämän myös Norppaan?"_

Norppa has the word "perinnekieli" in the title, where does this come from? Couldnt find it in Sisu?
![2024-04-30_perinteinen_NRPP](https://github.com/UniversityOfHelsinkiCS/palaute/assets/43775188/537cc0cb-6b5b-41d4-913b-83b290f7d161)

Norppa:
https://norppa.helsinki.fi/targets/72283150/edit

Sisu:
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/hy-opt-cur-2324-b1198c3e-4f79-4e34-ba7b-a91b8178d25c/information/basicinfo

**Comment by HRemonen** [comment]
This is because the Perinnekieli is the course unit and perintökieli is the course unit realisation.

Course unit: https://studies.helsinki.fi/kurssit/opintojakso/otm-4d672f96-4768-4599-95f7-9608d66c2631/ENG-Opt336?cpId=hy-lv-76

Course unit realisation: https://studies.helsinki.fi/kurssit/toteutus/hy-opt-cur-2324-b1198c3e-4f79-4e34-ba7b-a91b8178d25c/ENG-Opt336

The information is shown correctly in Norppa - however this leaves the question open if it's necessary to display the course unit name in feedback view at all.
