### ISSUE TITLE
KH30-003 Soveltavan psykologian kandiohjelma Norppaan (uusi SYKSY 2024)

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1325]
_Syksyllä starttaavaa uusi soveltavan psykologian kandiohjelma ja kävin siksi katsomassa, miltä Norpassa näyttää. Näkymässäni ei näy edes ylävalikkoa. Onkohan uusi koulutusohjelma ylipäätään Norpassa? Olen kyllä Sisussa hallintohenkilönä koulutusohjelman opintojaksoilla, mutta silti Norpan näkymä on tämä.  Samanlaiselta näyttää myös kollegani, psykologian koulutussuunnittelijan Norppa-näkymä. Puuttuukohan meiltä tarvittavat oikeudet?_

**Comment by HRemonen** [comment]
The organisation is in [Norppa](https://norppa.helsinki.fi/organisations/300-K003/settings) already, so now the issue is pretty much related to the access of this organisation.

## Investigation

I did some digging and found out that this Programme was missing from Jami completely and thus no-one could have access to the organisation and see it in their summary.

## Further steps

Need to [specify](https://github.com/UniversityOfHelsinkiCS/jami/blob/master/src/auth/IAMConfig.ts) the IAM groups which are able to see the programme and what ever
