### ISSUE TITLE
TAU-virkistys: avoin vs ei avoin

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1366]
if vain avoin selected, nothing is shown. this differs from the current situation in prod

![Image](https://github.com/user-attachments/assets/c279b1f2-58e2-4d28-add6-e56146f3b5b8)

**Comment by HRemonen** [comment]
Few overall fixes regarding this particular issue:

## Invalid fetching of Course Realisation Organisations

Probably the old code was working before for fetching the extra organisations, but after TAU changes something had changed and the logic was invalid.

Fixed by altering mapping logic:

https://github.com/UniversityOfHelsinkiCS/palaute/commit/16fdbe4a622cc8b03d12fc0da90521b7d62da348

## Invalid date range fixes

There were issues when some of the summaries had no time ranges at all, which caused errors to the users. Not directly related to this issue but still fixed at the same time:

https://github.com/UniversityOfHelsinkiCS/palaute/commit/db56e872d01ac6c3c1f5c424f16ec6b7707858d7


## Invalid summaries array given to the sumSummaries function

We were passing an filtered array of groupSummaries to the sumSummaries function:
https://github.com/UniversityOfHelsinkiCS/palaute/blob/1c9024bde4488d361545df45db745875a8067f67/src/server/services/summary/getOrganisationSummary.js#L80

This cause undeterministic behaviour based on what would be the first groupSummary gotten from the DB. 

Fixed by just giving the function sumSummaries the whole cu.groupSummaries:

https://github.com/UniversityOfHelsinkiCS/palaute/commit/fdc470864503175cfe97a4068718f409c3bfbf57
